"""new user model fields

Revision ID: 722159dddb17
Revises: 16a8e540c149
Create Date: 2020-02-05 22:01:51.870041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722159dddb17'
down_revision = '16a8e540c149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
