"""date added

Revision ID: e372fdef9c23
Revises: 3d4f359ded61
Create Date: 2020-02-07 12:41:08.050739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e372fdef9c23"
down_revision = "3d4f359ded61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("followers", "date_added", existing_type=sa.DATETIME())
    op.add_column("post", sa.Column("date_added", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("date_added", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "date_added")
    op.drop_column("post", "date_added")
    op.alter_column(
        "followers", "date_added", existing_type=sa.DATETIME(), nullable=False
    )
    # ### end Alembic commands ###
